export type Category = {
  id: number
  label: string
}

export type Skill = {
  name: string
  cat: number
  top?: boolean
}

export const SKILLS: Skill[] = [
  // Core expertise
  { name: "TypeScript", cat: 3, top: true },
  { name: "React Native", cat: 8, top: true },
  { name: "Next.js", cat: 1, top: true },
  { name: "NestJS", cat: 2, top: true },
  { name: "GraphQL", cat: 2, top: true },
  { name: "React", cat: 1,  top: true },
  { name: "AWS", cat: 6, top: true },
  // Additional skills — sorted by global importance/popularity
  { name: "Node.js", cat: 2 },
  { name: "Expo", cat: 8 },
  { name: "PostgreSQL", cat: 4 },
  { name: "Prisma", cat: 2 },
  { name: "Docker", cat: 5 },
  { name: "Apollo Client", cat: 1 },
  { name: "Apollo Server", cat: 2 },
  { name: "WebSockets", cat: 2 },
  { name: "JavaScript", cat: 3 },
  { name: "Redis", cat: 4 },
  { name: "MongoDB", cat: 4 },
  { name: "REST APIs", cat: 2 },
  { name: "Express", cat: 2 },
  { name: "GitHub Actions", cat: 5 },
  { name: "Tailwind CSS", cat: 1 },
  { name: "Redux", cat: 8 },
  { name: "React Query", cat: 1 },
  { name: "MySQL", cat: 4 },
  { name: "Supabase", cat: 4 },
  { name: "Stripe", cat: 7 },
  { name: "Jest", cat: 7 },
  { name: "Vercel", cat: 6 },
  { name: "Google Cloud", cat: 6 },
  { name: "TypeORM", cat: 2 },
  { name: "Vitest", cat: 7 },
  { name: "Figma", cat: 7 },
  { name: "Cloudflare", cat: 6 },
  { name: "Onfido", cat: 7 },
  { name: "Saferpay", cat: 7 },
  { name: "Fastlane", cat: 5 },
  { name: "CircleCI", cat: 5 },
  { name: "GitHub Copilot", cat: 7 },
  { name: "Claude Code", cat: 7 },
  { name: "Cursor", cat: 7 },
  { name: "DigitalOcean", cat: 6 },
  { name: "SQL", cat: 4 },
  { name: "Mongoose", cat: 2 },
  { name: "Sequelize", cat: 2 },
  { name: "Kotlin", cat: 3 },
  { name: "Swift", cat: 3 },
  { name: "Material UI", cat: 1 },
  { name: "Google Maps", cat: 7 },
  { name: "Detox", cat: 7 },
  { name: "Nginx", cat: 5 },
  { name: "MariaDB", cat: 4 },
  { name: "Redux-Saga", cat: 8 },
  { name: "Git", cat: 7 },
  { name: "D3.js", cat: 1 },
  { name: "SASS", cat: 1 },
  { name: "CSS Modules", cat: 1 },
  { name: "OneSignal", cat: 7 },
  { name: "FCM", cat: 7 },
  { name: "PM2", cat: 5 },
  { name: "Typegoose", cat: 2 },
  { name: "Web hooks", cat: 2 },
  { name: "SQLite", cat: 4 },
  { name: "MJML", cat: 7 },
  { name: "PDFKit", cat: 7 },
  { name: "Jira", cat: 7 },
  { name: "Trello", cat: 7 },
  { name: "Clickup", cat: 7 },
  { name: "Mocha", cat: 7 },
  { name: "Chai", cat: 7 },
];

export const CATEGORIES: Category[] = [
  { id: 0, label: "All" },
  { id: 8, label: "Mobile" },
  { id: 2, label: "Backend" },
  { id: 1, label: "Frontend" },
  { id: 3, label: "Languages" },
  { id: 4, label: "Database" },
  { id: 5, label: "DevOps" },
  { id: 6, label: "Cloud" },
  { id: 7, label: "Tools" },
];
