name: test
on:
  pull_request:
  push:
    branches: [master]

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      statuses: write 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --immutable
      - run: yarn check
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/
      - name: 'notify vercel'
        if: success()            # skips if any previous step failed
        uses: 'vercel/repository-dispatch/actions/status@v1'
        with:
          name: 'Vercel - portfolio: test'
