import type { ProjectBase } from "./types"

export const PROJECT_BASES: ProjectBase[] = [
  {
    id: 1,
    year: "2022–2026",
    link: {
      type: "web+mobile",
      url: "https://www.omegaeuropeanmasters.com/",
      appStore: "https://itunes.apple.com/us/app/omega-european-masters/id440218156",
      playStore: "https://market.android.com/details?id=ch.iomedia.oem2011",
    },
    featured: true,
    imageBg: "bg-gradient-to-br from-red-900/40 via-red-800/20 to-transparent",
    stack: ["React Native", "OneSignal", "Next.js", "NestJS", "Apollo Client/Server", "PostgreSQL", "Prisma", "Redis", "Bull", "Saferpay", "MJML", "Docker", "Digital Ocean"],
    stackFilters: ["React Native", "Next.js", "NestJS", "GraphQL"],
  },
  {
    id: 2,
    year: "2022–2026",
    link: {
      type: "web+mobile",
      url: "https://www.allsquaregolf.com/",
      appStore: "https://apps.apple.com/lu/app/all-square-golf/id793801635",
      playStore: "https://play.google.com/store/apps/details?id=com.allsquaregolf.rnapp",
    },
    imageBg: "bg-gradient-to-br from-green-900/30 to-transparent",
    stack: ["Next.js", "React Native", "Apollo Client/Server", "MariaDB", "Sequelize", "Stripe", "TypeScript"],
    stackFilters: ["Next.js", "React Native", "GraphQL"],
  },
  {
    id: 3,
    year: "2022–2026",
    link: {
      type: "mobile",
      appStore: "https://apps.apple.com/us/app/golf-club-crans-sur-sierre/id1382210998",
      playStore: "https://play.google.com/store/apps/details?id=ch.iomedia.golfcrans",
    },
    imageBg: "bg-gradient-to-br from-emerald-900/30 to-transparent",
    stack: ["React Native", "React Query", "REST APIs", "TypeScript"],
    stackFilters: ["React Native"],
  },
  {
    id: 4,
    year: "2017–2022",
    link: { type: "private" },
    imageBg: "bg-gradient-to-br from-sky-900/30 to-transparent",
    stack: ["React", "React Native", "Apollo Client/Server", "TypeScript", "MongoDB", "Express", "AWS EC2", "CircleCI", "Google Maps", "Redux + Saga"],
    stackFilters: ["React Native", "GraphQL", "AWS"],
    screenshots: [
      {
        src: "/projects-anonymized/pinclean.png",
        kind: "blurred",
        alt: "PinClean — anonymized preview",
        width: 1200,
        height: 675,
      },
    ],
  },
  {
    id: 5,
    year: "2017–2022",
    link: {
      type: "mobile",
      appStore: "https://apps.apple.com/ua/app/yamback/id1494671035",
      playStore: "https://play.google.com/store/apps/details?id=com.yamback.app",
    },
    stack: ["React Native", "Apollo Client/Server", "TypeScript", "MongoDB", "Express", "AWS EC2", "CircleCI", "Redux + Saga"],
    stackFilters: ["React Native", "GraphQL", "AWS"],
  },
  {
    id: 6,
    year: "2017–2022",
    link: {
      type: "mobile",
      appStore: "https://apps.apple.com/ch/app/b-sharpe-currency-exchange/id1499627995",
      playStore: "https://play.google.com/store/apps/details?id=com.bsharpe.app",
    },
    imageBg: "bg-gradient-to-br from-indigo-900/30 to-transparent",
    stack: ["React Native", "Redux + Saga", "React Query", "TypeScript", "Fastlane", "CircleCI", "GitHub Actions"],
    stackFilters: ["React Native"],
  },
  {
    id: 7,
    year: "2017–2022",
    link: {
      type: "mobile",
      appStore: "https://apps.apple.com/gb/app/wesyncup/id1347852079",
      playStore: "https://play.google.com/store/apps/details?id=com.wesyncup.wesyncup",
    },
    stack: ["React Native", "Redux + Saga", "GraphQL", "MongoDB", "Parse SDK", "TypeScript"],
    stackFilters: ["React Native", "GraphQL"],
  },
  {
    id: 8,
    year: "2017–2022",
    link: { type: "private" },
    stack: ["React Native", "Redux + Saga", "REST", "TypeScript", "Fastlane"],
    stackFilters: ["React Native"],
  },
  {
    id: 9,
    year: "2016–present",
    link: { type: "private" },
    stack: ["NestJS", "React Native", "Apollo Client/Server", "TypeScript", "GPIO", "Telegram API"],
    stackFilters: ["NestJS", "GraphQL"],
  },
  {
    id: 10,
    year: "2017–2022",
    link: { type: "private" },
    stack: ["React Native", "Redux + Saga", "GraphQL", "TypeScript", "Stripe", "PostgreSQL", "CircleCI"],
    stackFilters: ["React Native", "GraphQL"],
  },
  {
    id: 11,
    year: "2017–2022",
    link: { type: "private" },
    stack: ["React", "React Native", "Redux + Saga", "TypeScript", "Mongoose", "Apollo Client/Server"],
    stackFilters: ["React Native", "GraphQL"],
  },
  {
    id: 12,
    year: "2015–2017",
    link: { type: "private" },
    stack: ["React", "TypeScript", "REST", "Jest"],
    stackFilters: [],
  },
  {
    id: 13,
    year: "2015–2017",
    link: { type: "private" },
    stack: ["Angular", "JavaScript", "Node.js", "REST"],
    stackFilters: [],
  },
  {
    id: 14,
    year: "2015–2017",
    link: { type: "private" },
    stack: ["Marionette", "Backbone", "JavaScript", "REST"],
    stackFilters: [],
  },
]
