import type { ProjectBase } from "./types"

export const PROJECT_BASES: ProjectBase[] = [
  {
    id: 1,
    slug: "omega-european-masters",
    year: "2022–2026",
    link: {
      type: "web+mobile",
      url: "https://www.omegaeuropeanmasters.com/",
      appStore: "https://itunes.apple.com/us/app/omega-european-masters/id440218156",
      playStore: "https://market.android.com/details?id=ch.iomedia.oem2011",
    },
    featured: true,
    imageBg: "bg-gradient-to-br from-red-900/40 via-red-800/20 to-transparent",
    stack: ["TypeScript", "React Native", "Next.js", "NestJS", "Apollo Client", "Apollo Server", "PostgreSQL", "Prisma", "Redis", { name: "Bull", extra: true }, "Saferpay", "OneSignal", "MJML", "Docker", "DigitalOcean"],
    stackFilters: ["React Native", "Next.js", "NestJS", "GraphQL", "Saferpay"],
  },
  {
    id: 2,
    slug: "all-square-golf-social-network",
    year: "2022–2026",
    link: {
      type: "web+mobile",
      url: "https://www.allsquaregolf.com/",
      appStore: "https://apps.apple.com/lu/app/all-square-golf/id793801635",
      playStore: "https://play.google.com/store/apps/details?id=com.allsquaregolf.rnapp",
    },
    imageBg: "bg-gradient-to-br from-green-900/30 to-transparent",
    stack: ["TypeScript", "Next.js", "React Native", "Apollo Client", "Apollo Server", "MariaDB", "Sequelize", "Stripe"],
    stackFilters: ["Next.js", "React Native", "GraphQL", "Stripe"],
  },
  {
    id: 3,
    slug: "golf-club-crans-sur-sierre",
    year: "2022–2026",
    link: {
      type: "mobile",
      appStore: "https://apps.apple.com/us/app/golf-club-crans-sur-sierre/id1382210998",
      playStore: "https://play.google.com/store/apps/details?id=ch.iomedia.golfcrans",
    },
    imageBg: "bg-gradient-to-br from-emerald-900/30 to-transparent",
    stackFilters: ["React Native"],
    stack: ["TypeScript", "React Native", "React Query", "REST APIs"],
  },
  {
    id: 4,
    slug: "on-demand-car-wash",
    year: "2017–2022",
    link: { type: "private" },
    imageBg: "bg-gradient-to-br from-sky-900/30 to-transparent",
    stackFilters: ["React Native", "GraphQL", "AWS"],
    stack: ["TypeScript", "React", "React Native", "Apollo Client", "Apollo Server", "MongoDB", "Express", "AWS", "CircleCI", "Google Maps", "Redux", "Redux-Saga"],
    screenshots: [
      {
        src: "/projects-anonymized/pinclean.png",
        kind: "blurred",
        alt: "PinClean — anonymized preview",
        width: 1200,
        height: 675,
      },
    ],
  },
  {
    id: 5,
    slug: "yamback",
    year: "2017–2022",
    link: {
      type: "mobile",
      appStore: "https://apps.apple.com/ua/app/yamback/id1494671035",
      playStore: "https://play.google.com/store/apps/details?id=com.yamback.app",
    },
    stack: ["TypeScript", "React Native", "Apollo Client", "Apollo Server", "MongoDB", "Express", "AWS", "CircleCI", "Redux", "Redux-Saga"],
    stackFilters: ["React Native", "GraphQL", "AWS"],
  },
  {
    id: 6,
    slug: "b-sharpe-currency-exchange",
    year: "2017–2022",
    link: {
      type: "mobile",
      appStore: "https://apps.apple.com/ch/app/b-sharpe-currency-exchange/id1499627995",
      playStore: "https://play.google.com/store/apps/details?id=com.bsharpe.app",
    },
    imageBg: "bg-gradient-to-br from-indigo-900/30 to-transparent",
    stack: ["TypeScript", "React Native", "Redux", "Redux-Saga", "React Query", "Fastlane", "CircleCI", "GitHub Actions"],
    stackFilters: ["React Native"],
  },
  {
    id: 7,
    slug: "wesyncup",
    year: "2017–2022",
    link: {
      type: "mobile",
      appStore: "https://apps.apple.com/gb/app/wesyncup/id1347852079",
      playStore: "https://play.google.com/store/apps/details?id=com.wesyncup.wesyncup",
    },
    stack: ["TypeScript", "React Native", "Redux", "Redux-Saga", "GraphQL", "MongoDB", { name: "Parse SDK", extra: true }],
    stackFilters: ["React Native", "GraphQL"],
  },
  {
    id: 8,
    slug: "e-learning-mobile-platform",
    year: "2017–2022",
    link: { type: "private" },
    stack: ["TypeScript", "React Native", "Redux", "Redux-Saga", "REST APIs", "Fastlane"],
    stackFilters: ["React Native"],
  },
  {
    id: 9,
    slug: "home-security-platform",
    year: "2016–present",
    link: { type: "private" },
    stack: ["TypeScript", "NestJS", "React Native", "Apollo Client", "Apollo Server", { name: "GPIO", extra: true }, { name: "Telegram API", extra: true }],
    stackFilters: ["NestJS", "GraphQL"],
  },
  {
    id: 10,
    slug: "home-services-platform",
    year: "2017–2022",
    link: { type: "private" },
    stack: ["TypeScript", "React Native", "Redux", "Redux-Saga", "GraphQL", "Stripe", "PostgreSQL", "CircleCI"],
    stackFilters: ["React Native", "GraphQL", "Stripe"],
  },
  {
    id: 11,
    slug: "sporting-event-platform",
    year: "2017–2022",
    link: { type: "private" },
    stack: ["TypeScript", "React", "React Native", "Redux", "Redux-Saga", "Mongoose", "Apollo Client", "Apollo Server"],
    stackFilters: ["React Native", "GraphQL"],
  },
  {
    id: 12,
    slug: "survey-platform",
    year: "2015–2017",
    link: { type: "private" },
    stack: ["TypeScript", "React", "REST APIs", "Jest"],
    stackFilters: [],
  },
  {
    id: 13,
    slug: "search-bar-extension",
    year: "2015–2017",
    link: { type: "private" },
    stack: [{ name: "Angular", extra: true }, "JavaScript", "Node.js", "REST APIs"],
    stackFilters: [],
  },
  {
    id: 14,
    slug: "healthcare-system",
    year: "2015–2017",
    link: { type: "private" },
    stack: [{ name: "Marionette", extra: true }, { name: "Backbone", extra: true }, "JavaScript", "REST APIs"],
    stackFilters: [],
  },
]
