import type { ProjectContent } from "./types"

export const PROJECT_CONTENT_EN: Record<number, ProjectContent> = {
  1: {
    title: "Omega European Masters",
    titleGeneric: "Golf Tournament Platform",
    company: "Allsquare",
    industry: "Sports",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Tech Lead",
    skills: "Full stack + deployment",
    teamLabel: "7–11",
    teamDetail: "2–5 devs · 1–2 QA · 2 BA · 1 PO · 1 PM",
    scale: "Team",
    description: "Greenfield tournament platform built end-to-end — NestJS backend, Next.js web app, React Native apps with separate user and on-site admin modes (ticket scanning during live rounds), background workers, and a no-code page builder so non-technical staff run the entire product without a developer.",
    problem: "Founders needed a platform that could absorb live-event traffic spikes, scan tickets on-site, and let non-dev staff run the whole product — no developer in the loop after launch.",
    achievements: [
      "Live in production since 2022",
      "Handles concurrent-user spikes on tournament days",
      "On-site ticket scanning during live rounds",
      "Non-dev team runs the full product via self-serve CMS",
    ],
    duties: [
      "Platform architecture (web + mobile + backend)",
      "Backend development — solo for the final stretch",
      "Mobile development — solo for the final year",
      "High-load optimisation",
      "Deployment infra + CircleCI automation",
    ],
    badgeLabel: "High-load · no-code page builder · ticket system",
    homeCard: {
      problem: "Founders needed a platform that absorbs live-event traffic spikes, scans tickets on-site, and lets non-dev staff publish pages and toggle whole mobile-app sections — without a developer in the loop.",
      outcome: [
        "Live in production since 2022",
        "Absorbs concurrent-user spikes on tournament days",
        "Tickets scanned on-site during live rounds",
      ],
      buyerBadge: "Live-event scale · Self-serve CMS for non-devs",
    },
  },
  2: {
    title: "Golfers Social Network",
    titleGeneric: "Golf Social Network",
    company: "Allsquare",
    industry: "Social",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Developer",
    skills: "Full stack",
    teamLabel: "8",
    teamDetail: "4 devs · 1 QA · 1 BA · 1 PO · 1 PM",
    scale: "Team",
    description: "Shipped new revenue surfaces (booking, search) across web and mobile on a mature live codebase while rebuilding legacy modules in parallel. No feature-freeze for the migration.",
    problem: "Mature product needed new revenue surfaces (booking, search) and legacy modules modernised without freezing feature delivery.",
    achievements: [
      "Booking + search shipped across web + mobile on a live codebase",
      "Legacy modules rebuilt with zero user-visible regressions",
    ],
    duties: [
      "Web + mobile feature delivery",
      "Backend feature delivery",
      "Legacy module rebuilds",
    ],
    badgeLabel: "Mature · Legacy",
    homeCard: {
      problem: "Mature product needed new revenue surfaces (booking, search) and legacy modules modernised without freezing feature delivery.",
      outcome: [
        "Shipped booking + search across web + mobile on a live codebase",
        "Legacy modules rebuilt with zero user-visible regressions",
      ],
      buyerBadge: "Mature codebase · Ships without breaking",
    },
  },
  3: {
    title: "Golfcrans",
    titleGeneric: "Golf Club Booking App",
    company: "Allsquare",
    industry: "Sports",
    productType: "SaaS",
    devTypes: ["Mobile"],
    role: "Mobile Lead",
    skills: "Mobile app development",
    teamLabel: "8",
    teamDetail: "2 mobile devs · 1 backend · 1–2 QA · 2 BA · 1 PM",
    scale: "Team",
    description: "Led the React Native mobile build of a golf-club booking app end-to-end — architecture, feature delivery, and payments integration across iOS and Android.",
    problem: "Golf club needed a mobile booking app with integrated payments, owned end-to-end from architecture to App Store.",
    achievements: [
      "Mobile architecture owned start-to-finish",
      "Payments shipped across iOS + Android",
    ],
    duties: [
      "Mobile app architecture",
      "Mobile app development",
    ],
    badgeLabel: "Mobile App Lead · payments",
    homeCard: {
      problem: "Golf club needed a mobile booking app with integrated payments, led end-to-end.",
      outcome: [
        "Mobile architecture owned start-to-finish",
        "Payments shipped across iOS + Android",
      ],
      buyerBadge: "Mobile + payments · Lead ownership",
    },
  },
  4: {
    title: "PinClean",
    titleGeneric: "On-Demand Car Wash",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack + deployment",
    teamLabel: "3",
    teamDetail: "1 dev · 1 QA · 1 PM",
    scale: "Solo build",
    description: "Solo 0→1 build of an on-demand car-wash platform — customer mobile app, dispatcher web dashboard, backend, and infrastructure. Later re-launched in a second market.",
    problem: "Founder needed the whole on-demand service app — mobile, dispatcher dashboard, backend, infra — built solo and shipped in two markets.",
    achievements: [
      "Shipped mobile + web + backend + CI/CD as sole developer",
      "Launched in two markets (original + South Africa)",
      "In production for multiple years",
    ],
    duties: [
      "Platform architecture",
      "Web dashboard development",
      "Mobile app development",
      "Backend development",
      "Infrastructure & CI/CD setup",
    ],
    badgeLabel: "Full stack · Google Maps",
    homeCard: {
      problem: "Founder needed the whole on-demand service app — mobile, dispatcher dashboard, backend, infra — built solo, shipped in both the original market and a South Africa edition.",
      outcome: [
        "Shipped mobile + web + backend + CI/CD as sole developer",
        "Launched in two markets (original + South Africa)",
        "Years in production",
      ],
      buyerBadge: "Solo full-stack build · Service app from zero, two markets",
    },
  },
  5: {
    title: "Yamback",
    titleGeneric: "Last-Message Delivery App",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack + deployment",
    teamLabel: "5",
    teamDetail: "2 devs · 1 QA · 1 BA · 1 PM",
    scale: "Team",
    description: "0→1 build of a last-message delivery app — sends pre-written personal messages when the user stops checking in. Led a team of 5 through the full lifecycle and owned architecture across React Native, GraphQL/Apollo, MongoDB, and AWS.",
    problem: "Founders needed a reliable last-message delivery system — scheduling, recipient management, and push notifications across mobile and backend — shipped by a small team.",
    achievements: [
      "Led a team of 5 through full product lifecycle",
      "Backend-heavy split — ~60% backend, ~40% mobile",
      "Full system architecture: React Native + GraphQL + MongoDB + AWS",
    ],
    duties: [
      "Platform architecture",
      "Backend development (~60%)",
      "Mobile app development (~40%)",
      "Infrastructure & CI/CD setup",
    ],
  },
  6: {
    title: "B-Sharpe",
    titleGeneric: "Currency Exchange App",
    company: "Avocado Technology",
    industry: "Fintech",
    productType: "SaaS",
    devTypes: ["Mobile"],
    role: "Mobile Lead",
    skills: "Mobile app development",
    teamLabel: "9",
    teamDetail: "5 devs · 2 QA · 1 BA · 1 PM",
    scale: "Team",
    description: "Mobile lead for a Swiss fintech currency-exchange app. Owned mobile architecture end-to-end and set up automated iOS + Android release pipelines with Fastlane.",
    problem: "Swiss fintech needed a mobile client with compliant multi-step KYC signup and automated release pipelines across iOS + Android.",
    achievements: [
      "Onfido KYC integrated end-to-end",
      "Mobile CI/CD automated via Fastlane (CircleCI → GitHub Actions)",
    ],
    duties: [
      "Mobile app architecture",
      "Mobile app development",
      "iOS + Android release automation (Fastlane, CircleCI → GitHub Actions)",
    ],
    badgeLabel: "Mobile App Lead · Swiss Fintech",
    homeCard: {
      problem: "Swiss fintech needed a mobile client with a compliant multi-step signup (Onfido identity verification) and automated release pipelines across iOS + Android.",
      outcome: [
        "Onfido KYC integrated end-to-end",
        "Mobile CI/CD automated via Fastlane",
      ],
      buyerBadge: "Swiss fintech · KYC + regulatory-grade mobile",
    },
  },
  7: {
    title: "WeSyncUp",
    titleGeneric: "Scheduling App",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Developer",
    skills: "Mobile + partial backend",
    teamLabel: "8",
    teamDetail: "3 devs · 1 lead · 1–2 QA · 1 BA · 1 PM",
    scale: "Team",
    description: "Calendly-like mobile scheduling app for iOS and Android. Shipped mobile end-to-end with backend contributions and stronger test coverage.",
    problem: "Team needed a Calendly-like mobile scheduling app delivered across both iOS and Android with backend support.",
    achievements: [
      "iOS + Android delivered in parallel",
      "Backend contributions alongside mobile work",
      "Test coverage improved across the project",
    ],
    duties: [
      "iOS + Android mobile development",
      "Partial backend",
      "Test coverage expansion",
    ],
  },
  8: {
    title: "Government Learning Platform",
    titleGeneric: "E-Learning Platform",
    company: "Avocado Technology",
    industry: "Gov",
    productType: "SaaS",
    devTypes: ["Mobile"],
    role: "Developer",
    skills: "Mobile app development",
    teamLabel: "7",
    teamDetail: "2 devs · 1 lead · 2 QA · 1 BA · 1 PM",
    scale: "Team",
    description: "Government-commissioned e-learning + testing mobile app. Shipped iOS and Android simultaneously under a tight deadline.",
    problem: "Government commissioned a mobile e-learning platform with student testing, delivered under a tight deadline.",
    achievements: [
      "Delivered on time under tight government deadline",
      "iOS + Android shipped simultaneously",
    ],
    duties: [
      "iOS + Android mobile development",
      "Build automation",
    ],
  },
  9: {
    title: "MataPi",
    titleGeneric: "Home Security Platform",
    company: "Personal",
    industry: "IoT",
    productType: "IoT",
    devTypes: ["Full Stack"],
    role: "Developer",
    skills: "Full stack",
    teamLabel: "1",
    teamDetail: "Solo",
    scale: "Personal project",
    description: "Self-built home-security platform evolved over 10+ years across four architectures — from camera-to-Google-Drive, to a full backend + mobile + RFID + CO₂ system, to a lean Telegram-bot-controlled worker. Owner mindset on every iteration.",
    problem: "Needed a self-hosted home-security system that could evolve with the hardware — from basic camera recording to multi-sensor control with remote alerting.",
    achievements: [
      "Four architecture iterations over 10+ years",
      "RFID + CO₂ sensor support integrated",
      "Telegram bot + worker architecture for remote control",
    ],
    duties: [
      "System architecture across all versions",
      "Backend development",
      "Worker app (Raspberry Pi runner)",
      "Mobile app — v3",
      "Telegram bot — v4",
      "Hardware integration (GPIO, RFID, CO2 sensor)",
    ],
  },
  10: {
    title: "HiAlfred",
    titleGeneric: "Home Services Platform",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack",
    teamLabel: "3",
    teamDetail: "1 dev · 1 QA · 1 PM",
    scale: "Solo build",
    description: "Led the migration of a legacy homeowner-services platform onto a modern stack while shipping new mobile and backend features in parallel. No feature-freeze during migration.",
    problem: "Legacy codebase needed migration to a modern stack without pausing feature delivery for homeowners and service providers.",
    achievements: [
      "Legacy-to-modern migration completed solo",
      "Mobile + backend features shipped in parallel",
      "CI/CD automated with CircleCI",
    ],
    duties: [
      "Legacy codebase migration to modern stack",
      "Mobile feature delivery",
      "Backend updates",
      "CircleCI automation",
    ],
  },
  11: {
    title: "LCB Event Platform",
    titleGeneric: "Sporting Event Platform",
    company: "Avocado Technology",
    industry: "Sports",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack",
    teamLabel: "5",
    teamDetail: "3 devs · 1 QA · 1 PM",
    scale: "Team",
    description: "One-month 0→1 build of a sporting-event web + mobile proof of concept. Led a team of 5; web, mobile, and backend all from scratch, shipped in time for the event.",
    problem: "Sporting event needed a web + mobile proof of concept delivered from scratch in one month.",
    achievements: [
      "Led a team of 5 through one-month delivery",
      "Web + mobile + backend built from scratch",
    ],
    duties: [
      "System architecture",
      "Web app development",
      "Mobile app development",
      "Backend development",
    ],
  },
  12: {
    title: "Survey Platform",
    titleGeneric: "Survey Platform",
    company: "EngagePoint",
    industry: "Enterprise",
    productType: "SaaS",
    devTypes: ["Web"],
    role: "Developer",
    skills: "Web",
    teamLabel: "15–30",
    teamDetail: "Large cross-functional team",
    scale: "Team",
    description: "Enterprise SurveyMonkey-alternative with a dynamic questionnaire builder — many field types and cross-field conditional logic.",
    problem: "Enterprise needed a SurveyMonkey-like platform supporting many field types with cross-field conditional logic.",
    achievements: [
      "Dynamic questionnaire builder with conditional logic",
      "Cross-field linking for complex survey flows",
    ],
    duties: [
      "Feature development for dynamic questionnaire components",
      "Field cross-linking and conditional logic",
      "Unit testing",
    ],
  },
  13: {
    title: "Search Bar Extension",
    titleGeneric: "Search Bar Extension",
    company: "EngagePoint",
    industry: "Enterprise",
    productType: "Browser Extension",
    devTypes: ["Web"],
    role: "Developer",
    skills: "Web + backend",
    teamLabel: "14",
    teamDetail: "8 devs · 3 QA · 1 PM · 1 BA · 1 tech writer",
    scale: "Team",
    description: "Chrome extension to search through a corporate knowledge base and file storages, with multiple storage connectors.",
    problem: "Corporation needed a Chrome extension to search across multiple internal knowledge bases and file storages.",
    achievements: [
      "Multiple storage connector integrations shipped",
      "Chrome WebExtensions API implemented",
    ],
    duties: [
      "Chrome extension development (WebExtensions API)",
      "Multiple storage connector integrations",
      "Features and bugfixes",
    ],
  },
  14: {
    title: "Healthcare System",
    titleGeneric: "Healthcare System",
    company: "EngagePoint",
    industry: "Healthcare",
    productType: "SaaS",
    devTypes: ["Web"],
    role: "Developer",
    skills: "Web",
    teamLabel: "15",
    teamDetail: "8 devs · 4 QA · 1 PM · 1 BA · 1 tech writer",
    scale: "Team",
    description: "Large-scale web app for the US Affordable Care Act healthcare program, delivered inside a cross-functional team.",
    problem: "Large-scale ACA healthcare system required frontend development within a complex, cross-functional team.",
    achievements: [
      "SPA features delivered on ACA-scale project",
      "Legacy Backbone/Marionette codebase maintained",
    ],
    duties: [
      "SPA feature development",
      "Legacy Backbone/Marionette codebase work",
      "Cross-team code review",
    ],
  },
}
