import type { ProjectContent } from "./types"

export const PROJECT_CONTENT_EN: Record<number, ProjectContent> = {
  1: {
    title: "Omega European Masters",
    titleGeneric: "Golf Tournament Platform",
    company: "Allsquare",
    industry: "Sports",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Tech Lead",
    skills: "Full stack + deployment",
    teamLabel: "7–11",
    teamDetail: "2–5 devs · 1–2 QA · 2 BA · 1 PO · 1 PM",
    scale: "Team",
    description: "Large-scale golf tournament platform built from the ground up — a high-load, multi-component system spanning a NestJS backend, Next.js web app, React Native mobile app with separate user and admin modes (admin used on-site for ticket scanning during live events), background workers, and a no-code page builder enabling non-technical teams to manage the entire product independently.",
    problem: "Tournament organiser needed a platform that absorbs live-event traffic spikes, scans tickets on-site, and lets non-dev staff manage the entire product without a developer.",
    achievements: [
      "In production since 2022",
      "Peak concurrent users on tournament days",
      "On-site ticket scanning during live rounds",
      "Self-serve CMS — non-dev team manages the full product",
    ],
    duties: [
      "Architecture of the platform",
      "Web app development",
      "Mobile application development (last year completely solo)",
      "Backend development (almost completely solo)",
      "Highload optimisation",
      "Deployment infrastructure setup and support",
      "CircleCI builds automation",
      "Code review",
    ],
    badgeLabel: "High-load · no-code page builder · ticket system",
    homeCard: {
      problem: "Tournament organiser needed a platform that absorbs live-event traffic spikes, scans tickets on-site, and lets non-dev staff publish and edit pages and control whole platform parts — e.g. show/hide sections in the mobile app — without a developer in the loop.",
      outcome: [
        "In production since 2022",
        "Peak concurrent users on tournament days",
        "Tickets scanned on-site during live rounds",
      ],
      buyerBadge: "Live-event scale · Self-serve CMS for non-devs",
    },
  },
  2: {
    title: "Golfers Social Network",
    titleGeneric: "Golf Social Network",
    company: "Allsquare",
    industry: "Social",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Developer",
    skills: "Full stack",
    teamLabel: "8",
    teamDetail: "4 devs · 1 QA · 1 BA · 1 PO · 1 PM",
    scale: "Team",
    description: "Full-stack feature delivery for a large-scale golf social network across web and mobile on a mature, established codebase. Extended platform capabilities with new product sections including booking and search, complex interactive UI components, backend features, and legacy module modernisation.",
    problem: "Mature product needed new revenue surfaces (booking, search) and legacy modules modernised without freezing feature delivery.",
    achievements: [
      "Booking + search shipped across web + mobile on a live codebase",
      "Legacy modules rebuilt with zero user-visible regressions",
    ],
    duties: [
      "Web app development",
      "Mobile application development",
      "Backend development",
      "Code review",
    ],
    badgeLabel: "Mature · Legacy",
    homeCard: {
      problem: "Mature product needed new revenue surfaces (booking, search) and legacy modules modernised without freezing feature delivery.",
      outcome: [
        "Shipped booking + search across web + mobile on a live codebase",
        "Legacy modules rebuilt with zero user-visible regressions",
      ],
      buyerBadge: "Mature codebase · Ships without breaking",
    },
  },
  3: {
    title: "Golfcrans",
    titleGeneric: "Golf Club Booking App",
    company: "Allsquare",
    industry: "Sports",
    productType: "SaaS",
    devTypes: ["Mobile"],
    role: "Mobile Lead",
    skills: "Mobile app development",
    teamLabel: "8",
    teamDetail: "2 mobile devs · 1 backend · 1–2 QA · 2 BA · 1 PM",
    scale: "Team",
    description: "Led React Native mobile development for a golf-club booking platform with integrated payments. Owned mobile architecture, feature delivery, and code review.",
    problem: "Golf club needed a mobile booking app with integrated payments, owned end-to-end from architecture to App Store.",
    achievements: [
      "Mobile architecture owned start-to-finish",
      "Payments shipped across iOS + Android",
    ],
    duties: [
      "Mobile app architecture",
      "Mobile app development",
      "Code review",
    ],
    badgeLabel: "Mobile App Lead · payments",
    homeCard: {
      problem: "Golf club needed a mobile booking app with integrated payments, led end-to-end.",
      outcome: [
        "Mobile architecture owned start-to-finish",
        "Payments shipped across iOS + Android",
      ],
      buyerBadge: "Mobile + payments · Lead ownership",
    },
  },
  4: {
    title: "PinClean",
    titleGeneric: "On-Demand Car Wash",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack + deployment",
    teamLabel: "3",
    teamDetail: "1 dev · 1 QA · 1 PM",
    scale: "Solo build",
    description: "On-demand car washing platform connecting users with on-call washers via a mobile app and managing operations through a web dashboard. Built solo across all layers: mobile, web, backend, and infrastructure.",
    problem: "Founder needed the whole on-demand service app — mobile, dispatcher dashboard, backend, infra — built solo and shipped in two markets.",
    achievements: [
      "Shipped mobile + web + backend + CI/CD as sole developer",
      "Launched in two markets (original + South Africa)",
      "In production for multiple years",
    ],
    duties: [
      "Platform architecture",
      "Web dashboard development",
      "Mobile app development",
      "Backend development",
      "Infrastructure & CI/CD setup",
    ],
    badgeLabel: "Full stack · Google Maps",
    homeCard: {
      problem: "Founder needed the whole on-demand service app — mobile, dispatcher dashboard, backend, infra — built solo, shipped in both the original market and a South Africa edition.",
      outcome: [
        "Shipped mobile + web + backend + CI/CD as sole developer",
        "Launched in two markets (original + South Africa)",
        "Years in production",
      ],
      buyerBadge: "Solo full-stack build · Service app from zero, two markets",
    },
  },
  5: {
    title: "Yamback",
    titleGeneric: "Last-Message Delivery App",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack + deployment",
    teamLabel: "5",
    teamDetail: "2 devs · 1 QA · 1 BA · 1 PM",
    scale: "Team",
    description: "Last-message delivery app that automatically sends pre-written personal messages to recipients when the user stops checking in. Led a team of 5, designed the full system architecture across React Native, GraphQL/Apollo, MongoDB, and AWS, and drove hands-on development of backend and mobile.",
    problem: "Product required a reliable last-message delivery system with scheduling, recipient management, and push notifications across mobile and backend.",
    achievements: [
      "Led a team of 5 through full product lifecycle",
      "Backend-heavy split — ~60% backend, ~40% mobile",
      "Full system architecture: React Native + GraphQL + MongoDB + AWS",
    ],
    duties: [
      "Platform architecture",
      "Backend development (~60% of time)",
      "Mobile app development (~40% of time)",
      "Code review",
      "Infrastructure & CI/CD setup",
    ],
  },
  6: {
    title: "B-Sharpe",
    titleGeneric: "Currency Exchange App",
    company: "Avocado Technology",
    industry: "Fintech",
    productType: "SaaS",
    devTypes: ["Mobile"],
    role: "Mobile Lead",
    skills: "Mobile app development",
    teamLabel: "9",
    teamDetail: "5 devs · 2 QA · 1 BA · 1 PM",
    scale: "Team",
    description: "Swiss fintech currency-exchange platform mobile app. Owned the mobile architecture and established mobile CI/CD automation with Fastlane across CircleCI and later GitHub Actions.",
    problem: "Swiss fintech needed a mobile client with compliant multi-step KYC signup and automated release pipelines across iOS + Android.",
    achievements: [
      "Onfido KYC integrated end-to-end",
      "Mobile CI/CD automated via Fastlane (CircleCI → GitHub Actions)",
    ],
    duties: [
      "Mobile app architecture",
      "Mobile app development",
      "Code review",
      "CircleCI / GitHub Actions builds automation",
    ],
    badgeLabel: "Mobile App Lead · Swiss Fintech",
    homeCard: {
      problem: "Swiss fintech needed a mobile client with a compliant multi-step signup (Onfido identity verification) and automated release pipelines across iOS + Android.",
      outcome: [
        "Onfido KYC integrated end-to-end",
        "Mobile CI/CD automated via Fastlane",
      ],
      buyerBadge: "Swiss fintech · KYC + regulatory-grade mobile",
    },
  },
  7: {
    title: "WeSyncUp",
    titleGeneric: "Scheduling App",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Mobile"],
    role: "Developer",
    skills: "Mobile + partial backend",
    teamLabel: "8",
    teamDetail: "3 devs · 1 lead · 1–2 QA · 1 BA · 1 PM",
    scale: "Team",
    description: "Calendly-like scheduling application for mobile. Delivered iOS and Android development, contributed to backend, improved test coverage, and participated in code review throughout the project.",
    problem: "Team needed a Calendly-like mobile scheduling app delivered across both iOS and Android with backend support.",
    achievements: [
      "iOS + Android delivered in parallel",
      "Backend contributions alongside mobile work",
      "Test coverage improved across the project",
    ],
    duties: [
      "Mobile application development (iOS + Android)",
      "Partial backend development",
      "Test coverage",
      "Code review",
    ],
  },
  8: {
    title: "Government Learning Platform",
    titleGeneric: "E-Learning Platform",
    company: "Avocado Technology",
    industry: "Gov",
    productType: "SaaS",
    devTypes: ["Mobile"],
    role: "Developer",
    skills: "Mobile app development",
    teamLabel: "7",
    teamDetail: "2 devs · 1 lead · 2 QA · 1 BA · 1 PM",
    scale: "Team",
    description: "Government-commissioned e-learning platform for Ukraine with student testing functionality. Delivered under tight deadlines across iOS and Android.",
    problem: "Government commissioned a mobile e-learning platform with student testing, delivered under a tight deadline.",
    achievements: [
      "Delivered on time under tight government deadline",
      "iOS + Android shipped simultaneously",
    ],
    duties: [
      "Mobile application development (iOS + Android)",
      "Build automation",
      "Code review",
    ],
  },
  9: {
    title: "MataPi",
    titleGeneric: "Home Security Platform",
    company: "Personal",
    industry: "IoT",
    productType: "IoT",
    devTypes: ["Full Stack"],
    role: "Developer",
    skills: "Full stack",
    teamLabel: "1",
    teamDetail: "Solo",
    scale: "Personal project",
    description: "Own home security platform built over 10+ years through four iterations — from simple camera recording synced to Google Drive, to a full system with backend, mobile notifications, RFID and CO2 sensor support, and finally a leaner worker + Telegram bot architecture for remote control and alerting.",
    problem: "Needed a self-hosted home security system that evolved over a decade — from camera recording to a full multi-sensor platform with remote control.",
    achievements: [
      "Four architecture iterations over 10+ years",
      "RFID + CO₂ sensor support integrated",
      "Telegram bot + worker architecture for remote control",
    ],
    duties: [
      "System architecture across all versions",
      "Backend development",
      "Worker app (Raspberry Pi runner)",
      "Mobile app — v3",
      "Telegram bot — v4",
      "Hardware integration (GPIO, RFID, CO2 sensor)",
    ],
  },
  10: {
    title: "HiAlfred",
    titleGeneric: "Home Services Platform",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack",
    teamLabel: "3",
    teamDetail: "1 dev · 1 QA · 1 PM",
    scale: "Solo build",
    description: "Platform connecting homeowners with service providers for household tasks. Led migration of the legacy codebase to a modern stack, delivered new features across mobile and backend, and automated builds with CircleCI.",
    problem: "Legacy codebase needed migration to a modern stack while continuing to ship new features for homeowners and service providers.",
    achievements: [
      "Legacy-to-modern migration completed solo",
      "Mobile + backend features shipped in parallel",
      "CI/CD automated with CircleCI",
    ],
    duties: [
      "Legacy codebase migration to modern stack",
      "Mobile application development",
      "Minor backend updates",
      "CircleCI builds automation",
    ],
  },
  11: {
    title: "LCB Event Platform",
    titleGeneric: "Sporting Event Platform",
    company: "Avocado Technology",
    industry: "Sports",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack",
    teamLabel: "5",
    teamDetail: "3 devs · 1 QA · 1 PM",
    scale: "Team",
    description: "Event website and mobile app proof of concept for a sporting event. Led a team of 5 through a tight one-month delivery, building web, mobile, and backend from scratch.",
    problem: "Sporting event needed a web + mobile proof of concept delivered from scratch in one month.",
    achievements: [
      "Led a team of 5 through one-month delivery",
      "Web + mobile + backend built from scratch",
    ],
    duties: [
      "System architecture",
      "Web app development",
      "Mobile app development",
      "Backend development",
    ],
  },
  12: {
    title: "Survey Platform",
    titleGeneric: "Survey Platform",
    company: "EngagePoint",
    industry: "Enterprise",
    productType: "SaaS",
    devTypes: ["Web"],
    role: "Developer",
    skills: "Web",
    teamLabel: "15–30",
    teamDetail: "Large cross-functional team",
    scale: "Team",
    description: "SurveyMonkey-like platform with dynamic questionnaire creation. Supports many field types and cross-field linking for conditional logic.",
    problem: "Enterprise needed a SurveyMonkey-like platform supporting many field types with cross-field conditional logic.",
    achievements: [
      "Dynamic questionnaire builder with conditional logic",
      "Cross-field linking for complex survey flows",
    ],
    duties: [
      "Feature development for dynamic questionnaire components",
      "Field cross-linking and conditional logic",
      "Unit testing",
    ],
  },
  13: {
    title: "Search Bar Extension",
    titleGeneric: "Search Bar Extension",
    company: "EngagePoint",
    industry: "Enterprise",
    productType: "Browser Extension",
    devTypes: ["Web"],
    role: "Developer",
    skills: "Web + backend",
    teamLabel: "14",
    teamDetail: "8 devs · 3 QA · 1 PM · 1 BA · 1 tech writer",
    scale: "Team",
    description: "Chrome extension to search through a corporate knowledge base and file storages, with multiple storage connectors.",
    problem: "Corporation needed a Chrome extension to search across multiple internal knowledge bases and file storages.",
    achievements: [
      "Multiple storage connector integrations shipped",
      "Chrome WebExtensions API implemented",
    ],
    duties: [
      "Chrome extension development (WebExtensions API)",
      "Multiple storage connector integrations",
      "Features and bugfixes",
    ],
  },
  14: {
    title: "Healthcare System",
    titleGeneric: "Healthcare System",
    company: "EngagePoint",
    industry: "Healthcare",
    productType: "SaaS",
    devTypes: ["Web"],
    role: "Developer",
    skills: "Web",
    teamLabel: "15",
    teamDetail: "8 devs · 4 QA · 1 PM · 1 BA · 1 tech writer",
    scale: "Team",
    description: "Complex web application for the US healthcare system, related to the Affordable Care Act program. Built as part of a large cross-functional team.",
    problem: "Large-scale ACA healthcare system required frontend development within a complex, cross-functional team.",
    achievements: [
      "SPA features delivered on ACA-scale project",
      "Legacy Backbone/Marionette codebase maintained",
    ],
    duties: [
      "SPA feature development",
      "Legacy Backbone/Marionette codebase work",
      "Cross-team code review",
    ],
  },
}
