import type { ProjectContent } from "./types"

export const PROJECT_CONTENT_EN: Record<number, ProjectContent> = {
  1: {
    title: "Omega European Masters",
    titleGeneric: "Golf Tournament Platform",
    company: "All Square",
    industry: "Sports",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Tech Lead",
    skills: "Full stack + deployment",
    teamLabel: "7–11",
    teamDetail: "2–5 devs · 1–2 QA · 2 BA · 1 PO · 1 PM",
    scale: "Team",
    shapes: ["greenfield"],
    description: "Greenfield tournament platform, live since 2022. Web app with an admin dashboard and a built-in no-code page builder, iOS and Android apps with separate user and on-site admin modes for ticket scanning, and a NestJS backend with background workers. Held the whole platform alone in the final year, including a full content migration from the old site.",
    problem: "A platform the founders' team runs themselves — page authoring, mobile-app sections, and on-site ticket scanning during live rounds, without a developer in the loop after launch.",
    achievements: [
      "Three tournament editions, four years in production",
      "Thousands of concurrent users on tournament days",
      "On-site ticket scanning during live rounds",
      "Operations team ships product changes without a developer in the loop",
      "Full content migration from the old site (pages, media, historical results)",
    ],
    duties: [
      "Platform architecture across web, mobile, and backend",
      "Held the whole platform alone in the final year",
      "Content migration from the old site (pages, media, historical results)",
      "High-load optimisation for tournament-day traffic",
      "Deployment infra + CircleCI automation",
    ],
    badgeLabel: "High-load · no-code page builder · ticket system",
    homeCard: {
      problem: "A platform the founders' team runs themselves — publishing pages, toggling whole mobile-app sections, and scanning tickets on-site during live rounds, without a developer in the loop after launch.",
      outcome: [
        "Four years live, three tournament editions",
        "Thousands of concurrent users on tournament days",
        "On-site ticket scanning during live rounds",
        "Held the whole platform alone in the final year",
      ],
      buyerBadge: "Live-event scale · Self-serve CMS for non-devs",
    },
  },
  2: {
    title: "Golfers Social Network",
    titleGeneric: "Golf Social Network",
    company: "All Square",
    industry: "Social",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Developer",
    skills: "Full stack",
    teamLabel: "8",
    teamDetail: "4 devs · 1 QA · 1 BA · 1 PO · 1 PM",
    scale: "Team",
    shapes: ["mature"],
    description: "Worked inside a mature, live golf social network on Allsquare's main product. Shipped brand-new booking and search flows alongside an incremental rewrite of legacy modules, with no feature-freeze and no user-visible regressions.",
    problem: "A mature, live product where booking and search had to ship across web and mobile while legacy modules were rewritten underneath, with no feature-freeze and no user-visible regressions.",
    achievements: [
      "Legacy modules rebuilt with zero user-visible regressions",
      "Brand-new booking and search flows shipped across web + mobile on a live codebase",
      "No feature-freeze during the legacy rewrite",
      "Legacy modernised: HoCs and class components to hooks, JS to TS, manual GraphQL to codegen",
    ],
    duties: [
      "New-feature delivery across web, mobile, and backend",
      "Incremental rewrites of legacy modules without breaking production",
      "Coordinating rewrite work alongside ongoing feature delivery",
      "Working inside a live codebase shared with a 4-dev team",
    ],
    badgeLabel: "Mature · Legacy",
    homeCard: {
      problem: "A mature, live product where booking and search had to ship across web and mobile while legacy modules were rewritten underneath, with no feature-freeze and no user-visible regressions.",
      outcome: [
        "Legacy rebuilt with zero user-visible regressions",
        "Brand-new booking and search flows shipped on a live codebase",
        "No feature-freeze during the legacy rewrite",
      ],
      buyerBadge: "Mature codebase · Ships without breaking",
    },
  },
  3: {
    title: "Golfcrans",
    titleGeneric: "Golf Club Booking App",
    company: "All Square",
    industry: "Sports",
    productType: "SaaS",
    devTypes: ["Mobile"],
    role: "Mobile Lead",
    skills: "Mobile app development",
    teamLabel: "8",
    teamDetail: "2 mobile devs · 1 backend · 1–2 QA · 2 BA · 1 PM",
    scale: "Team",
    shapes: ["greenfield"],
    description: "React Native booking app for a Swiss golf club, built end-to-end as the mobile lead. Owned the architecture, feature delivery, and Saferpay integration on top of a dedicated REST backend; shipped to both the App Store and Google Play.",
    problem: "A native iOS and Android booking app for the club, owned end-to-end by one mobile lead from architecture and payments through to both stores.",
    achievements: [
      "Live on the App Store and Google Play",
      "Single mobile lead from first commit to launch",
      "Saferpay payments shipping on iOS + Android",
      "Booking + payment flow without abandoned-cart issues",
    ],
    duties: [
      "Mobile architecture for iOS and Android",
      "Feature delivery across both platforms",
      "Saferpay integration and booking-flow logic",
      "App Store and Google Play submission and updates",
    ],
    badgeLabel: "Mobile App Lead · payments",
    homeCard: {
      problem: "A native iOS and Android booking app for the club, owned end-to-end by one mobile lead from architecture and payments through to both stores.",
      outcome: [
        "Single mobile lead from first commit to both stores",
        "Saferpay payments shipping on iOS + Android",
        "Booking + payment flow without abandoned-cart issues",
      ],
      buyerBadge: "Mobile + payments · Lead ownership",
    },
  },
  4: {
    title: "PinClean",
    titleGeneric: "On-Demand Car Wash",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack + deployment",
    teamLabel: "3",
    teamDetail: "1 dev · 1 QA · 1 PM",
    scale: "Solo build",
    shapes: ["greenfield"],
    description: "Solo 0→1 build of an on-demand car-wash platform: customer mobile app, dispatcher web dashboard, backend, and AWS infrastructure, all owned by one developer. Live in the original market 2018–2020, then productised and re-launched in South Africa.",
    problem: "An on-demand service platform built solo from zero. Customer mobile app, dispatcher web dashboard, backend, and infra. Shipped, productised, and re-launched in a second market.",
    achievements: [
      "Solo build of mobile + dispatcher web + backend + infra",
      "Live in the original market 2018–2020",
      "Productised and re-launched in South Africa",
    ],
    duties: [
      "Platform architecture across mobile, web, backend, and infra",
      "Customer-facing React Native app for iOS and Android",
      "Dispatcher web dashboard for job dispatch and order tracking",
      "Apollo + Express + MongoDB backend on AWS",
      "CI/CD on CircleCI and AWS provisioning",
    ],
    badgeLabel: "Full stack · Google Maps",
    homeCard: {
      problem: "An on-demand service platform built solo from zero. Customer mobile app, dispatcher web dashboard, backend, and infra. Shipped, productised, and re-launched in a second market.",
      outcome: [
        "Solo build of mobile + dispatcher web + backend + infra",
        "Live in the original market 2018–2020",
        "Productised and re-launched in South Africa",
      ],
      buyerBadge: "Solo full-stack build · Service app from zero, two markets",
    },
  },
  5: {
    title: "Yamback",
    titleGeneric: "Last-Message Delivery App",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack + deployment",
    teamLabel: "5",
    teamDetail: "2 devs · 1 QA · 1 BA · 1 PM",
    scale: "Team",
    shapes: ["greenfield"],
    description: "0→1 build of a dead-man's-switch messaging app: sends pre-written personal messages (text, video, documents) to chosen recipients when the user stops checking in. Recipients without the app open the delivery on a web view via a one-time token in the notification, SMS, or email. Led the team through the full lifecycle and owned the architecture end-to-end.",
    problem: "A messaging app that delivers pre-written content (text, video, documents) to chosen recipients when the user stops checking in, reachable even by recipients who never installed the app. Reliability over arbitrary time windows was the whole product.",
    achievements: [
      "Live on the App Store and Google Play, with a recipient web view",
      "Led the team through the full 0→1 lifecycle",
      "Multi-channel delivery: push to app users, plus one-time-token SMS/email links to a recipient web view for everyone else",
      "Architecture owned end-to-end across mobile, web, backend, and AWS",
    ],
    duties: [
      "Platform architecture across mobile, web, backend, and infra",
      "React Native app for iOS and Android",
      "Recipient-facing web app with one-time-token anonymous access",
      "Apollo + Express backend on MongoDB, with check-in monitoring and multi-channel delivery pipeline",
      "AWS provisioning and CircleCI pipelines",
    ],
  },
  6: {
    title: "B-Sharpe",
    titleGeneric: "Currency Exchange App",
    company: "Avocado Technology",
    industry: "Fintech",
    productType: "SaaS",
    devTypes: ["Mobile"],
    role: "Mobile Lead",
    skills: "Mobile app development",
    teamLabel: "9",
    teamDetail: "5 devs · 2 QA · 1 BA · 1 PM",
    scale: "Team",
    shapes: ["greenfield"],
    description: "Mobile lead on a Swiss fintech currency-exchange app, live in four languages (DE, FR, IT, EN) on both stores. Owned the architecture end-to-end: a complex multi-step regulated signup with Onfido KYC, mobile observability and attribution (Crashlytics, Firebase Analytics, AppsFlyer), an externalised translations workflow, and iOS/Android release pipelines (CircleCI + Fastlane, later migrated to GitHub Actions).",
    problem: "A Swiss fintech mobile client where a complex multi-step regulated signup (Onfido KYC), four-language localization, and signed iOS/Android release pipelines all had to ship production-grade.",
    achievements: [
      "Live on the App Store and Google Play in a regulated Swiss market",
      "Complex multi-step Onfido KYC signup with nested sub-flows",
      "Mobile observability and attribution: Crashlytics, Firebase Analytics, AppsFlyer",
      "Localization in DE/FR/IT/EN, edited by non-devs from a third-party translation platform",
      "iOS + Android release pipelines built on CircleCI + Fastlane, then migrated to GitHub Actions",
    ],
    duties: [
      "Mobile architecture for iOS and Android",
      "Complex multi-step Onfido KYC signup integration",
      "Crashlytics, Firebase Analytics, and AppsFlyer integration",
      "Localization workflow: separate repo synced from a third-party translation platform",
      "iOS + Android release pipelines (CircleCI + Fastlane, later migrated to GitHub Actions)",
    ],
    badgeLabel: "Mobile App Lead · Swiss Fintech",
    homeCard: {
      problem: "A Swiss fintech mobile client where a complex multi-step regulated signup (Onfido KYC), four-language localization, and signed iOS/Android release pipelines all had to ship production-grade.",
      outcome: [
        "Live on the App Store and Google Play in a regulated Swiss market",
        "Complex multi-step Onfido KYC signup with nested sub-flows",
        "Mobile observability and attribution: Crashlytics, Firebase Analytics, AppsFlyer",
      ],
      buyerBadge: "Swiss fintech · KYC + regulatory-grade mobile",
    },
  },
  7: {
    title: "WeSyncUp",
    titleGeneric: "Scheduling App",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Developer",
    skills: "Mobile + partial backend",
    teamLabel: "8",
    teamDetail: "3 devs · 1 lead · 1–2 QA · 1 BA · 1 PM",
    scale: "Team",
    shapes: ["greenfield"],
    description: "Calendly-style mobile scheduling app on React Native, live on both stores. Reconciles availability across Google, iCloud, and Outlook calendars for multiple participants, with push reminders and cross-region time-zone handling. Backend contributions against Parse SDK and GraphQL, Sentry for crash and error tracking, and test coverage raised from 0 to over 80%.",
    problem: "A Calendly-style scheduling app where multi-participant calendar reconciliation across Google, iCloud, and Outlook had to work correctly on iOS and Android.",
    achievements: [
      "Live on the App Store and Google Play",
      "Multi-participant calendar reconciliation across Google, iCloud, and Outlook",
      "Cross-region time-zone correctness with push reminders",
      "Test coverage raised from 0 to over 80% on a shared codebase",
    ],
    duties: [
      "iOS and Android feature development on React Native + Redux-Saga",
      "Calendar provider integrations: Google, iCloud, Outlook OAuth + free/busy sync",
      "Multi-participant timeslot reconciliation logic",
      "Backend contributions on Parse SDK and GraphQL",
      "Sentry integration for crash and error reporting",
      "Test coverage expansion from 0 to over 80%",
    ],
  },
  8: {
    title: "Government Learning Platform",
    titleGeneric: "E-Learning Platform",
    company: "Avocado Technology",
    industry: "Gov",
    productType: "SaaS",
    devTypes: ["Mobile"],
    role: "Developer",
    skills: "Mobile app development",
    teamLabel: "7",
    teamDetail: "2 devs · 1 lead · 2 QA · 1 BA · 1 PM",
    scale: "Team",
    shapes: ["greenfield"],
    description: "Mobile e-learning and student-assessment app for a government client, delivered on React Native with REST APIs, Fastlane-automated releases, and Sentry for crash reporting. Offline content delivery and offline assessments, with iOS and Android shipped simultaneously inside a 3-month contractual window.",
    problem: "A government e-learning and assessment app, delivered offline-capable on iOS and Android within a 3-month contractual deadline.",
    achievements: [
      "iOS and Android shipped simultaneously to a 3-month contractual deadline",
      "Offline content delivery and offline student assessments",
      "Fastlane-automated release pipeline for both platforms",
    ],
    duties: [
      "iOS and Android feature development on React Native + Redux-Saga",
      "Offline content delivery and assessment logic",
      "REST API integration on the mobile client",
      "Fastlane release automation for iOS and Android",
      "Sentry integration for crash and error reporting",
    ],
  },
  9: {
    title: "MataPi",
    titleGeneric: "Home Security Platform",
    company: "Personal",
    industry: "IoT",
    productType: "IoT",
    devTypes: ["Full Stack"],
    role: "Developer",
    skills: "Full stack",
    teamLabel: "1",
    teamDetail: "Solo",
    scale: "Personal project",
    shapes: ["greenfield"],
    description: "Solo, self-hosted home-security platform in its tenth year, rebuilt four times. v1 streamed camera footage to Google Drive. v2 added a full backend. v3 grew into a full mobile app with RFID access and a CO₂ sensor. v4 deliberately cut everything back to a Raspberry Pi running a Telegram-bot worker: camera capture + cloud upload, alerts and control via chat, no web UI, no mobile app, no cloud bills. Running today across three locations.",
    problem: "A self-hosted home-security system rebuilt four times across a decade, from camera-to-cloud, through a full mobile + sensor stack, to a leaner Telegram-bot worker running on a Raspberry Pi today.",
    achievements: [
      "Four architecture iterations over a decade (2016 to today)",
      "Deliberate v3 → v4 simplification: full mobile + sensor stack to a Telegram-bot worker on a Raspberry Pi",
      "Hardware integration: GPIO, RFID, CO₂ sensor on Raspberry Pi",
      "Running today across three locations with zero cloud bills",
    ],
    duties: [
      "System architecture across all four versions",
      "NestJS backend (current stack) and prior backend versions",
      "Worker app on Raspberry Pi (v4)",
      "React Native mobile app (v3)",
      "Telegram bot for control and alerts (v4)",
      "Hardware integration via GPIO (RFID reader, CO₂ sensor)",
    ],
  },
  10: {
    title: "HiAlfred",
    titleGeneric: "Home Services Platform",
    company: "Avocado Technology",
    industry: "Services",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack",
    teamLabel: "3",
    teamDetail: "1 dev · 1 QA · 1 PM",
    scale: "Solo build",
    shapes: ["mature"],
    description: "Solo modernisation of a two-sided homeowner-services marketplace. Migrated the mobile codebase from JavaScript to TypeScript and from class components to hooks, consolidated a state-management mess of React Context + Apollo + Redux onto Apollo cache as the source of truth, re-integrated the Stripe payment flow against the modernised backend, and added CircleCI + Fastlane release automation. New features shipped throughout, with no feature-freeze and no user-visible regressions.",
    problem: "A two-sided homeowner-services marketplace whose mobile codebase had to be modernised solo, with payments re-integrated and CI/CD added, all while continuing to ship features without regressions.",
    achievements: [
      "Legacy mobile codebase modernised solo on a live two-sided marketplace",
      "No feature-freeze: new mobile and backend features shipped during the migration",
      "Zero user-visible regressions during the modernisation",
      "Modernised: JS to TS, class components to hooks, state-management consolidated onto Apollo cache",
      "CI/CD introduced: CircleCI + Fastlane release automation",
    ],
    duties: [
      "Solo modernisation of a legacy React Native mobile codebase",
      "JavaScript to TypeScript and class-components to hooks migration",
      "State-management consolidation: React Context + Apollo + Redux → Apollo cache as source of truth",
      "Stripe payment-flow re-integration against the modernised backend",
      "CircleCI + Fastlane release automation introduced",
    ],
  },
  11: {
    title: "LCB Event Platform",
    titleGeneric: "Sporting Event Platform",
    company: "Avocado Technology",
    industry: "Sports",
    productType: "SaaS",
    devTypes: ["Full Stack"],
    role: "Full-Stack Lead",
    skills: "Full stack",
    teamLabel: "5",
    teamDetail: "3 devs · 1 QA · 1 PM",
    scale: "Team",
    shapes: ["greenfield"],
    description: "One-month 0→1 build of a sporting-event proof-of-concept platform: a React web app, a React Native mobile app, and an Apollo + Mongoose backend, all from scratch. Covered event agenda, signup/sign-in, news, and webviews of pages from the existing event site. Led the team and delivered demo-ready before the event opened.",
    problem: "A sporting-event proof-of-concept platform with web, mobile, and backend all built from scratch and demo-ready in time for the event opening, on a one-month deadline.",
    achievements: [
      "Three platforms (web + mobile + backend) shipped from scratch in one month",
      "Led the team through a one-month 0→1 cycle to a fixed event deadline",
      "Demo-ready before the event opened",
    ],
    duties: [
      "Platform architecture across web, mobile, and backend",
      "React web app from scratch",
      "React Native mobile app from scratch",
      "Apollo + Mongoose backend from scratch",
      "Coordinating delivery across three platforms inside the one-month window",
    ],
  },
  12: {
    title: "Survey Platform",
    titleGeneric: "Survey Platform",
    company: "EngagePoint",
    industry: "Enterprise",
    productType: "SaaS",
    devTypes: ["Web"],
    role: "Developer",
    skills: "Web",
    teamLabel: "15–30",
    teamDetail: "Large cross-functional team",
    scale: "Team",
    shapes: ["mature"],
    description: "Inside a large cross-functional team, built dynamic questionnaire components for an enterprise SurveyMonkey-alternative — 20+ field types, a conditional-logic engine covering visibility, required-state, and value-derivation rules, and virtualised rendering for long forms.",
    problem: "An enterprise SurveyMonkey-alternative whose dynamic questionnaire builder had to support 20+ field types, cross-field conditional logic, and long-form rendering performance.",
    achievements: [
      "Shipped dynamic questionnaire components inside a large enterprise codebase",
      "Conditional-logic engine across visibility, required-state, and value-derivation rules",
      "20+ field types supported in a single questionnaire builder",
      "Long-form rendering optimised via virtualisation",
    ],
    duties: [
      "React feature development for the dynamic questionnaire builder",
      "Conditional-logic engine: visibility, required-state, and value-derivation rules across fields",
      "Long-form rendering performance work (virtualisation)",
      "Unit-test coverage for new feature work",
    ],
  },
  13: {
    title: "Search Bar Extension",
    titleGeneric: "Search Bar Extension",
    company: "EngagePoint",
    industry: "Enterprise",
    productType: "Browser Extension",
    devTypes: ["Web"],
    role: "Developer",
    skills: "Web + backend",
    teamLabel: "14",
    teamDetail: "8 devs · 3 QA · 1 PM · 1 BA · 1 tech writer",
    scale: "Team",
    shapes: ["mature"],
    description: "Chrome extension that searches across a corporate knowledge base and multiple file-storage providers (internal corporate storage, databases, Google Drive, Dropbox, Confluence/SharePoint), built on the WebExtensions API with an Angular UI and a Node.js backend that normalises results across providers. Delivered inside an 8-dev team.",
    problem: "A Chrome extension that searches across a corporate knowledge base and multiple file-storage providers, with a unified result format across heterogeneous APIs.",
    achievements: [
      "Connectors integrated across internal corporate storage, databases, Google Drive, Dropbox, and Confluence/SharePoint",
      "Result-format normalisation across heterogeneous provider APIs",
      "Chrome WebExtensions extension shipping to corporate users",
    ],
    duties: [
      "Chrome extension development on the WebExtensions API",
      "Connector integrations: internal corporate storage, databases, Google Drive, Dropbox, Confluence/SharePoint",
      "Result-format normalisation across heterogeneous provider APIs",
      "Angular front-end and Node.js service work",
    ],
  },
  14: {
    title: "Healthcare System",
    titleGeneric: "Healthcare System",
    company: "EngagePoint",
    industry: "Healthcare",
    productType: "SaaS",
    devTypes: ["Web"],
    role: "Developer",
    skills: "Web",
    teamLabel: "15",
    teamDetail: "8 devs · 4 QA · 1 PM · 1 BA · 1 tech writer",
    scale: "Team",
    shapes: ["mature"],
    description: "Shipped SPA features into a federal-scale US Affordable Care Act healthcare web app on a legacy Backbone/Marionette frontend. Section 508 accessibility compliance and performance optimisation on long multi-step enrolment flows. Inside an 8-dev cross-functional team.",
    problem: "A federal-scale ACA healthcare web app on a legacy Backbone/Marionette frontend, with Section 508 accessibility and performance demands on long enrolment flows.",
    achievements: [
      "SPA features shipped on a federal-scale ACA healthcare web app",
      "Section 508 accessibility compliance on form-heavy enrolment flows",
      "Performance optimisation on long multi-step enrolment UI",
      "Legacy Backbone/Marionette codebase maintained alongside new feature work",
    ],
    duties: [
      "SPA feature development on the ACA healthcare web app",
      "Section 508 accessibility work on form components",
      "Performance optimisation on long multi-step enrolment flows",
      "Legacy Backbone/Marionette codebase maintenance",
      "Cross-team code review",
    ],
  },
}
